Repository Maum-eum/Server, pull requests merged in 2025-02, with the labels that each got.

#20 DOCS : Repository Label 세팅 + 깃 이슈, PR 템플릿 세팅
  .github/ISSUE_TEMPLATE/basic-issue.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/PULL_REQUEST_TEMPLATE
  .github/pull_request_template.md
  src/main/java/com/example/springserver/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/springserver/controller/elder/ElderController.java
  src/main/java/com/example/springserver/converter/elder/ElderConverter.java
  src/main/java/com/example/springserver/domain/entity/Admin.java
  src/main/java/com/example/springserver/domain/entity/Center.java
  src/main/java/com/example/springserver/domain/entity/Certificate.java
  src/main/java/com/example/springserver/domain/entity/DementiaSymptom.java
  src/main/java/com/example/springserver/domain/entity/Experience.java
  src/main/java/com/example/springserver/domain/entity/JobRequirementCondition.java
  src/main/java/com/example/springserver/domain/entity/Location.java
  src/main/java/com/example/springserver/domain/entity/Match.java
  src/main/java/com/example/springserver/domain/entity/Member.java
  src/main/java/com/example/springserver/domain/entity/RequiredWorkingHour.java
  src/main/java/com/example/springserver/domain/entity/RequirementCondition.java
  src/main/java/com/example/springserver/domain/entity/Sido.java
  src/main/java/com/example/springserver/domain/entity/Sigungu.java
  src/main/java/com/example/springserver/domain/entity/WorkLocation.java
  src/main/java/com/example/springserver/domain/entity/WorkTime.java
  src/main/java/com/example/springserver/domain/entity/elder/Elder.java
  src/main/java/com/example/springserver/domain/entity/elder/ElderEntity.java
  src/main/java/com/example/springserver/dto/elder/ElderResponseDto.java
  src/main/java/com/example/springserver/repository/center/CenterRepository.java
  src/main/java/com/example/springserver/repository/elder/ElderRepository.java
  src/main/java/com/example/springserver/service/elder/ElderService.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: CHORE 🌟, SETTING 🌎, DOCS 📘

#35 구직조건 등록 API 구현
  src/main/java/com/example/springserver/domain/caregiver/controller/CaregiverController.java
  src/main/java/com/example/springserver/domain/caregiver/converter/CaregiverConverter.java
  src/main/java/com/example/springserver/domain/caregiver/dto/request/CaregiverRequestDTO.java
  src/main/java/com/example/springserver/domain/caregiver/dto/response/CaregiverResponseDTO.java
  src/main/java/com/example/springserver/domain/caregiver/entity/Caregiver.java
  src/main/java/com/example/springserver/domain/caregiver/entity/JobCondition.java
  src/main/java/com/example/springserver/domain/caregiver/entity/WorkLocation.java
  src/main/java/com/example/springserver/domain/caregiver/entity/WorkTime.java
  src/main/java/com/example/springserver/domain/caregiver/entity/enums/Week.java
  src/main/java/com/example/springserver/domain/caregiver/repository/JobConditionRepository.java
  src/main/java/com/example/springserver/domain/caregiver/repository/WorkLocationRepository.java
  src/main/java/com/example/springserver/domain/caregiver/repository/WorkTimeRepository.java
  src/main/java/com/example/springserver/domain/caregiver/service/CareGiverService.java
  src/main/java/com/example/springserver/domain/center/converter/TimeConverter.java
  src/main/java/com/example/springserver/global/apiPayload/format/ErrorCode.java
  src/main/java/com/example/springserver/global/common/entity/BaseEntity.java
  src/main/java/com/example/springserver/repository/location/LocationRepository.java
Labels: FEAT💎

#49 요양보호사 매칭 응답 API 구현
  src/main/java/com/example/springserver/domain/caregiver/controller/CaregiverController.java
  src/main/java/com/example/springserver/domain/caregiver/dto/request/CaregiverRequestDTO.java
  src/main/java/com/example/springserver/domain/caregiver/dto/response/CaregiverResponseDTO.java
  src/main/java/com/example/springserver/domain/caregiver/service/CareGiverService.java
  src/main/java/com/example/springserver/domain/center/dto/request/RecruitRequestDto.java
  src/main/java/com/example/springserver/domain/center/entity/Match.java
  src/main/java/com/example/springserver/domain/center/entity/RecruitTime.java
  src/main/java/com/example/springserver/domain/center/entity/enums/MatchStatus.java
  src/main/java/com/example/springserver/domain/center/entity/enums/RecruitStatus.java
  src/main/java/com/example/springserver/domain/center/repository/MatchRepository.java
  src/main/java/com/example/springserver/global/apiPayload/format/ErrorCode.java
Labels: FEAT💎

#51 Feat/#50
  src/main/java/com/example/springserver/domain/caregiver/controller/CaregiverController.java
  src/main/java/com/example/springserver/domain/caregiver/converter/CaregiverConverter.java
  src/main/java/com/example/springserver/domain/caregiver/dto/request/CaregiverRequestDTO.java
  src/main/java/com/example/springserver/domain/caregiver/dto/response/CaregiverResponseDTO.java
  src/main/java/com/example/springserver/domain/caregiver/entity/Caregiver.java
  src/main/java/com/example/springserver/domain/caregiver/entity/JobCondition.java
  src/main/java/com/example/springserver/domain/caregiver/entity/enums/ScheduleAvailability.java
  src/main/java/com/example/springserver/domain/caregiver/service/CareGiverService.java
  src/main/java/com/example/springserver/domain/center/converter/TimeConverter.java
  src/main/java/com/example/springserver/domain/center/service/RecruitService.java
  src/main/java/com/example/springserver/global/apiPayload/format/ErrorCode.java
Labels: BUG 🐞, FEAT💎, OPTIMALIZATION ✔️

#62 feat: 요양보호사 매칭현황리스트 API 구현(테스트 미완료)
  src/main/java/com/example/springserver/domain/caregiver/controller/CaregiverController.java
  src/main/java/com/example/springserver/domain/caregiver/dto/request/CaregiverRequestDTO.java
  src/main/java/com/example/springserver/domain/caregiver/dto/response/CaregiverResponseDTO.java
  src/main/java/com/example/springserver/domain/caregiver/service/CareGiverService.java
  src/main/java/com/example/springserver/domain/center/entity/Match.java
  src/main/java/com/example/springserver/domain/center/entity/enums/MatchStatus.java
  src/main/java/com/example/springserver/domain/center/repository/MatchRepository.java
Labels: FEAT💎

#64 요양보호사 근무요청리스트 조회 API 구현
  src/main/java/com/example/springserver/domain/caregiver/controller/CaregiverController.java
  src/main/java/com/example/springserver/domain/caregiver/converter/CaregiverConverter.java
  src/main/java/com/example/springserver/domain/caregiver/dto/request/CaregiverRequestDTO.java
  src/main/java/com/example/springserver/domain/caregiver/dto/response/CaregiverResponseDTO.java
  src/main/java/com/example/springserver/domain/caregiver/entity/JobCondition.java
  src/main/java/com/example/springserver/domain/caregiver/entity/enums/Sexual.java
  src/main/java/com/example/springserver/domain/caregiver/service/CareGiverService.java
  src/main/java/com/example/springserver/domain/center/repository/MatchRepository.java
Labels: FEAT💎

#67 chore: 패키지구조변경
  src/main/java/com/example/springserver/domain/caregiver/controller/CaregiverController.java
  src/main/java/com/example/springserver/domain/caregiver/controller/JobConditionController.java
  src/main/java/com/example/springserver/domain/caregiver/converter/CaregiverConverter.java
  src/main/java/com/example/springserver/domain/caregiver/converter/JobConditionConverter.java
  src/main/java/com/example/springserver/domain/caregiver/dto/request/CaregiverRequestDto.java
  src/main/java/com/example/springserver/domain/caregiver/dto/request/JobConditionRequestDto.java
  src/main/java/com/example/springserver/domain/caregiver/dto/response/CaregiverResponseDto.java
  src/main/java/com/example/springserver/domain/caregiver/dto/response/JobConditionResponseDto.java
  src/main/java/com/example/springserver/domain/caregiver/entity/Caregiver.java
  src/main/java/com/example/springserver/domain/caregiver/entity/JobCondition.java
  src/main/java/com/example/springserver/domain/caregiver/service/CareGiverService.java
  src/main/java/com/example/springserver/domain/caregiver/service/CommonService.java
  src/main/java/com/example/springserver/domain/caregiver/service/JobConditionService.java
  src/main/java/com/example/springserver/domain/center/repository/MatchRepository.java
  src/main/java/com/example/springserver/domain/match/controller/MatchController.java
  src/main/java/com/example/springserver/domain/match/dto/request/MatchRequestDto.java
  src/main/java/com/example/springserver/domain/match/dto/response/MatchResponseDto.java
  src/main/java/com/example/springserver/domain/match/entity/Match.java
  src/main/java/com/example/springserver/domain/match/service/MatchService.java
  src/main/java/com/example/springserver/global/utils/FormatUtils.java
  src/main/java/com/example/springserver/service/JoinService.java
  src/main/java/com/example/springserver/service/location/LocationService.java
  src/main/resources/application.yml
Labels: CHORE 🌟

#79 hotfix: Sql 데이터 테이블 명 수정
  src/main/resources/center.sql
  src/main/resources/data.sql
Labels: HOT FIX 🔥

#87 Feat: 근무요청 API 구현 및 AWS S3 버전 업데이트
  build.gradle
  src/main/java/com/example/springserver/domain/match/controller/MatchController.java
  src/main/java/com/example/springserver/domain/match/dto/response/MatchResponseDto.java
  src/main/java/com/example/springserver/domain/match/entity/Match.java
  src/main/java/com/example/springserver/domain/match/service/MatchService.java
  src/main/java/com/example/springserver/global/security/config/S3Config.java
  src/main/java/com/example/springserver/service/S3Service.java
Labels: BUG 🐞, FEAT💎

#94 feat: 관리자 매칭 조율 및 수락/거절 , 추천결과 상세조회 API 구현
  build.gradle
  src/main/java/com/example/springserver/domain/center/entity/Care.java
  src/main/java/com/example/springserver/domain/center/repository/MatchRepository.java
  src/main/java/com/example/springserver/domain/match/controller/MatchController.java
  src/main/java/com/example/springserver/domain/match/dto/response/MatchResponseDto.java
  src/main/java/com/example/springserver/domain/match/service/MatchService.java
  src/main/java/com/example/springserver/global/apiPayload/format/ErrorCode.java
  src/main/java/com/example/springserver/global/config/ModelMapperConfig.java
  src/main/java/com/example/springserver/global/security/config/SecurityConfig.java
Labels: FEAT💎

#99 Feat: 관리자 매칭 조율 및 수락/거절 , 추천결과 상세조회 API 구현
  src/main/java/com/example/springserver/domain/caregiver/converter/JobConditionConverter.java
  src/main/java/com/example/springserver/domain/match/controller/MatchController.java
  src/main/java/com/example/springserver/domain/match/converter/MatchConverter.java
  src/main/java/com/example/springserver/domain/match/dto/response/MatchResponseDto.java
  src/main/java/com/example/springserver/domain/match/entity/Match.java
  src/main/java/com/example/springserver/domain/match/service/MatchService.java
  src/main/java/com/example/springserver/global/config/ModelMapperConfig.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: FEAT💎

#102 fix: updateCareGiverDto 변수명 response와 통일
  src/main/java/com/example/springserver/domain/caregiver/dto/request/CaregiverRequestDto.java
Labels: HOT FIX 🔥
